# Generated by Django 2.2.7 on 2019-11-26 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adstable',
            name='ads_click_num',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
