# Generated by Django 2.2.7 on 2019-11-26 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20191126_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customertable',
            name='customer_id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
