# Generated by Django 2.2.7 on 2019-11-26 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20191126_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customertable',
            name='customer_data_sources_id',
            field=models.PositiveSmallIntegerField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='customertable',
            name='customer_id',
            field=models.AutoField(db_index=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customertable',
            name='customer_region2_cn',
            field=models.CharField(db_index=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='customertable',
            name='customer_region2_en',
            field=models.CharField(db_index=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='customertable',
            name='customer_trades_id',
            field=models.PositiveSmallIntegerField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='datasourcestable',
            name='data_sources_id',
            field=models.AutoField(db_index=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='datasourcestable',
            name='data_sources_name_cn',
            field=models.CharField(db_index=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='datasourcestable',
            name='data_sources_name_en',
            field=models.CharField(db_index=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='tradestable',
            name='trades_id',
            field=models.AutoField(db_index=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tradestable',
            name='trades_name_cn',
            field=models.CharField(db_index=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='tradestable',
            name='trades_name_en',
            field=models.CharField(db_index=True, max_length=64, null=True),
        ),
    ]
