# Generated by Django 2.2.7 on 2019-11-30 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20191130_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customertable',
            name='customer_company_name_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customertable',
            name='customer_email',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customertable',
            name='customer_facebook',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customertable',
            name='customer_fax',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customertable',
            name='customer_line',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customertable',
            name='customer_linkedin',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customertable',
            name='customer_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customertable',
            name='customer_post_code',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customertable',
            name='customer_skype',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customertable',
            name='customer_tel',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customertable',
            name='customer_website',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customertable',
            name='customer_wechat',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customertable',
            name='customer_whatsapp',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
