# Generated by Django 2.2.7 on 2019-12-10 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20191201_0454'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotCountryTable',
            fields=[
                ('hot_country_id', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('hot_country_cn', models.CharField(db_index=True, max_length=64, null=True)),
                ('hot_country_place', models.PositiveSmallIntegerField(default=0)),
                ('hot_country_state', models.PositiveSmallIntegerField(default=1)),
                ('hot_country_isdel', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'hot_country_table',
            },
        ),
        migrations.AlterField(
            model_name='adstable',
            name='ads_id',
            field=models.AutoField(db_index=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='evaluationtable',
            name='evaluation_id',
            field=models.AutoField(db_index=True, primary_key=True, serialize=False),
        ),
    ]
