# Generated by Django 2.2.7 on 2019-12-10 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20191210_1844'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotcountrytable',
            name='hot_country_place',
        ),
    ]
